djcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView, 
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
    )
from django.urls import path,include
from leads import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.LandingPageView.as_view(), name="landing-page"),
    path('leads/', include("leads.urls", namespace="leads")),
    path('agents/', include("agents.urls", namespace="agents")),
    path('signup/', views.SignupView.as_view(), name="signup"),
    path('reset-password/', PasswordResetView.as_view(), name="reset-password"),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path

from . import views

app_name = "leads"

urlpatterns = [
    path('', views.LeadListView.as_view(), name='lead-list'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='lead-detail'),
    path('<int:pk>/update/', views.LeadUpdateView.as_view(), name='lead-update'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='lead-delete'),
    path('<int:pk>/assign-agent/', views.AssignAgentView.as_view(), name='assign-agent'),
    path('<int:pk>/category/', views.LeadCategoryUpdateView.as_view(), name='lead-category-update'),
    path('create/', views.LeadCreateView.as_view(), name='lead-create'),
    path('create-category/', views.CategoryCreateView.as_view(), name='category-create'),
    path('category/', views.CategoryListView.as_view(), name='category-list'),
    path('category/<int:pk>/update', views.CategoryUpdateView.as_view(), name='category-update'),
    path('category/<int:pk>/delete', views.CategoryDeleteView.as_view(), name='category-delete'),
    path('category/<int:pk>/', views.CategoryDetailView.as_view(), name='category-detail'),
]

leads/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser



class User(AbstractUser):
    is_organisor = models.BooleanField(default=True)
    is_agent = models.BooleanField(default=False)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class Lead(models.Model):
    first_name = models.CharField('性',max_length=20)
    last_name = models.CharField('名',max_length=20)
    age = models.IntegerField('年齢',default=0)
    organisation = models.ForeignKey(UserProfile,on_delete=models.CASCADE)
    agent = models.ForeignKey("Agent",verbose_name="代理", null=True, blank=True, on_delete=models.SET_NULL)
    category = models.ForeignKey("Category",verbose_name="カテゴリー", related_name="leads", null=True, blank=True, on_delete=models.SET_NULL)
    description = models.TextField('説明')
    date_added = models.DateTimeField(auto_now_add=True)
    phone_number = models.CharField('携帯',max_length=20)
    email = models.EmailField('メール')

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organisation = models.ForeignKey(UserProfile,on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user.email

class Category(models.Model):
    name = models.CharField('カテゴリ名',max_length=30)
    organisation = models.ForeignKey(UserProfile,on_delete=models.CASCADE)

    def __str__(self):
        return self.name

def post_user_created_signal(sender,instance,created,**kwargs):
    print(instance,created)
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(post_user_created_signal,sender=User)

leads/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField
from .models import Lead, Agent, Category

User = get_user_model()

class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            "first_name", "last_name","age", "agent", "description",  "phone_number", "email",
        )


class LeadForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    age = forms.IntegerField(min_value=0)

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)
        field_classes = {"username": UsernameField}

class AssignAgentForm(forms.Form):
    agent = forms.ModelChoiceField(queryset=Agent.objects.none())

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")
        print(request.user)
        agents = Agent.objects.filter(organisation=request.user.userprofile)
        super(AssignAgentForm,self).__init__(*args, **kwargs)
        self.fields["agent"].queryset = agents

class LeadCategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            "category",
        )

class CategoryModelForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = (
            'name',
        )

leads/views.py
from django.core.mail import send_mail
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from agents.mixins import OrganisorAndLoginRequiredMixin
from .models import Category, Lead, Agent 
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView, FormView
from .forms import LeadForm, LeadModelForm, CustomUserCreationForm , AssignAgentForm, LeadCategoryUpdateForm, CategoryModelForm

#CRUD


class SignupView(CreateView):
    template_name = "registration/signup.html"
    form_class = CustomUserCreationForm
    
    def get_success_url(self):
        # return "/leads"
        return reverse("login")

class LandingPageView(TemplateView):
    template_name = 'landing.html'

def landing_page(request):
    return render(request, "landing.html")

class LeadListView(LoginRequiredMixin, ListView):
    template_name = "leads/lead_list.html"
    
    context_object_name = "leads"

    def get_queryset(self):
        user = self.request.user

        # initial qs of leads for the entire organisation
        if user.is_organisor:
            queryset = Lead.objects.filter(
                organisation=user.userprofile, 
                agent__isnull=False
            )
        else:
            queryset = Lead.objects.filter(organisation=user.agent.organisation, agent__isnull=False)
            # filter for the agent that is logged in
            queryset = queryset.filter(agent__user=user)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(LeadListView, self).get_context_data(**kwargs)
        user = self.request.user
        if user.is_organisor:
            queryset = Lead.objects.filter(
                organisation = user.userprofile, 
                agent__isnull = True
            )
            context.update({
                "unassigned_leads": queryset,
            })
        return context

def lead_list(request):
    leads = Lead.objects.all()
    context = {
        "leads": leads
    }
    return render(request , "leads/lead_list.html", context)

class LeadDetailView(LoginRequiredMixin,DetailView):
    template_name = "leads/lead_detail.html"
    context_object_name = "lead"

    def get_queryset(self):
        user = self.request.user

        # initial qs of leads for the entire organisation
        if user.is_organisor:
            queryset = Lead.objects.filter(organisation=user.userprofile)
        else:
            queryset = Lead.objects.filter(organisation=user.agent.organisation)
            # filter for the agent that is logged in
            queryset = queryset.filter(agent__user=user)
        return queryset

def lead_detail(request, pk):
    lead = Lead.objects.get(id=pk)
    context = {
        "lead": lead
    }
    return render(request , "leads/lead_detail.html", context)

class LeadCreateView(OrganisorAndLoginRequiredMixin,CreateView):
    template_name = "leads/lead_create.html"
    form_class = LeadModelForm
    
    def get_success_url(self):
        # return "/leads"
        return reverse("leads:lead-list")

    def form_valid(self, form):
        lead = form.save(commit=False)
        lead.organisation = self.request.user.userprofile
        # TODO send email
        send_mail(
            subject="A lead has been created",
            message="Go to the site to see the new lead",
            from_email = "test@test.com",
            recipient_list=["test2@test.com"]
        )
        return super(LeadCreateView, self).form_valid(form)

def lead_create(request):
    form = LeadModelForm()
    if request.method == "POST":
        print("Receiving a post request")
        form = LeadModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(("/leads"))
    context = {
        "form": form
    }
    return render(request, "leads/lead_create.html", context)

class LeadUpdateView(OrganisorAndLoginRequiredMixin,UpdateView):
    template_name = "leads/lead_update.html"
    form_class = LeadModelForm
    
    def get_queryset(self):
        user = self.request.user             
        # initial qs of leads for the entire organisation
        return Lead.objects.filter(organisation=user.userprofile)
    
    def get_success_url(self):
        # return "/leads"
        return reverse("leads:lead-list")

def lead_update(request, pk):
    lead = Lead.objects.get(id=pk)
    form = LeadModelForm(instance=lead)
    if request.method == "POST":
        form = LeadModelForm(request.POST, instance=lead)
        if form.is_valid():
            form.save()
            return redirect("/leads")
    context = {
        "form": form,
        "lead": lead
    }
    return render(request, "leads/lead_update.html", context)

class LeadDeleteView(OrganisorAndLoginRequiredMixin,DeleteView):
    template_name = "leads/lead_delete.html"
    
    def get_success_url(self):
        # return "/leads"
        return reverse("leads:lead-list")

    def get_queryset(self):
        user = self.request.user             
        # initial qs of leads for the entire organisation
        return Lead.objects.filter(organisation=user.userprofile)

def lead_delete(request, pk):
    lead = Lead.objects.get(id=pk)
    lead.delete()
    return redirect("/leads")

class  AssignAgentView(OrganisorAndLoginRequiredMixin, FormView):
    template_name = "leads/assign_agent.html" 
    form_class = AssignAgentForm

    def get_form_kwargs(self,**kwargs):
        kwargs = super(AssignAgentView, self).get_form_kwargs(**kwargs)
        kwargs.update({
            "request": self.request
        })
        return kwargs

    def get_success_url(self):
        # return "/leads"
        return reverse("leads:lead-list")

    def form_valid(self, form):
        agent = form.cleaned_data["agent"]
        lead = Lead.objects.get(id=self.kwargs["pk"])
        lead.agent = agent
        lead.save()
        return super(AssignAgentView, self).form_valid(form)

class CategoryListView(LoginRequiredMixin, ListView):
    template_name = "leads/category_list.html"
    context_object_name = "category_list"

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        user = self.request.user

        if user.is_organisor:
            queryset = Lead.objects.filter(
                organisation=user.userprofile,                 
            )
        else:
            queryset = Lead.objects.filter(organisation=user.agent.organisation)
        context.update({
            "unassigned_lead_count" : queryset.filter(category__isnull=True).filter().count()
        })       
        return context

    def get_queryset(self):
        user = self.request.user

        # initial qs of leads for the entire organisation
        if user.is_organisor:
            queryset = Category.objects.filter(
                organisation=user.userprofile,                 
            )
        else:
            queryset = Category.objects.filter(organisation=user.agent.organisation)       
        return queryset

class CategoryDetailView(LoginRequiredMixin, DetailView):
    template_name = "leads/category_detail.html"
    context_object_name = "category"    

   
    def get_queryset(self):
        user = self.request.user
        # initial qs of leads for the entire organisation
        if user.is_organisor:
            queryset = Category.objects.filter(
                organisation=user.userprofile,                 
            )
        else:
            queryset = Category.objects.filter(organisation=user.agent.organisation)       
        return queryset
class CategoryCreateView(OrganisorAndLoginRequiredMixin,CreateView):
    template_name = "leads/category_create.html"
    form_class = CategoryModelForm
    
    def get_success_url(self):
        # return "/leads"
        return reverse("leads:category-list")
    
    def form_valid(self, form):
        category = form.save(commit=False)
        category.organisation = self.request.user.userprofile
        category.save()
        return super(CategoryCreateView, self).form_valid(form)

class CategoryUpdateView(OrganisorAndLoginRequiredMixin,UpdateView):
    template_name = "leads/category_update.html"
    form_class = CategoryModelForm
    
    def get_success_url(self):
        # return "/leads"
        return reverse("leads:category-list")

    def get_queryset(self):
        user = self.request.user
        # initial qs of leads for the entire organisation
        if user.is_organisor:
            queryset = Category.objects.filter(
                organisation=user.userprofile,                 
            )
        else:
            queryset = Category.objects.filter(organisation=user.agent.organisation)       
        return queryset

    
class CategoryDeleteView(OrganisorAndLoginRequiredMixin, DeleteView):
    template_name = "leads/category_delete.html"

    def get_success_url(self):
        return reverse("leads:category-list")

    def get_queryset(self):
        user = self.request.user
        # initial queryset of leads for the entire organisation
        if user.is_organisor:
            queryset = Category.objects.filter(
                organisation=user.userprofile
            )
        else:
            queryset = Category.objects.filter(
                organisation=user.agent.organisation
            )
        return queryset


class LeadCategoryUpdateView(LoginRequiredMixin, UpdateView):
    template_name = "leads/lead_category_update.html"
    form_class = LeadCategoryUpdateForm
    
    
    def get_queryset(self):
        user = self.request.user             
        # initial qs of leads for the entire organisation
        if user.is_organisor:
            queryset = Lead.objects.filter(organisation=user.userprofile)
        else:

leads/templates/leads/assign_agent.html
{% extends "base.html" %} {% load tailwind_filters %} {% block content %}

<div class="max-w-lg mx-auto">
    <a class="hover:text-blue-500" href="{% url 'leads:lead-list' %}"
        >顧客リストに戻る</a
    >
    <div class="py-5 border-t border-gray-200">
        <h1 class="text-4xl text-gray-800">
            この顧客にエージェントを割り当てる
        </h1>
    </div>
    <form method="post" class="mt-5">
        {% csrf_token %} {{ form|crispy }}
        <button
            type="submit"
            class="
                w-full
                text-white
                bg-blue-500
                hover:bg-blue-600
                px-3
                py-2
                rounded-md
            "
        >
            確認
        </button>
    </form>
</div>

{% endblock content %}

leads/templates/leads/category_detail.html
{% extends "base.html" %} {% block content %}
<div class="max-w-lg mx-auto">
    <section class="text-gray-600 body-font">
        <div class="container px-5 py-24 mx-auto">
            <div class="flex flex-col text-center w-full mb-20">
                <h1
                    class="
                        sm:text-4xl
                        text-3xl
                        font-medium
                        title-font
                        mb-2
                        text-gray-900
                    "
                >
                    {{category.name}}
                </h1>
                <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
                    これらはカテゴリーの下の顧客です
                </p>
                <a
                    href="{% url 'leads:category-update' category.pk %}"
                    class="hover:text-blue-500"
                    >更新</a
                ><a
                    href="{% url 'leads:category-delete' category.pk %}"
                    class="hover:text-blue-500"
                    >削除</a
                >
            </div>
            <div class="lg:w-2/3 w-full mx-auto overflow-auto">
                <table class="table-auto w-full text-left whitespace-no-wrap">
                    <thead>
                        <tr>
                            <th
                                class="
                                    px-4
                                    py-3
                                    title-font
                                    tracking-wider
                                    font-medium
                                    text-gray-900 text-sm
                                    bg-gray-100
                                    rounded-tl rounded-bl
                                "
                            >
                                性
                            </th>
                            <th
                                class="
                                    px-4
                                    py-3
                                    title-font
                                    tracking-wider
                                    font-medium
                                    text-gray-900 text-sm
                                    bg-gray-100
                                "
                            >
                                名
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for lead in category.leads.all %}
                        <tr>
                            <td class="px-4 py-3">
                                <a
                                    class="hover:text-blue-500"
                                    href="{% url 'leads:lead-detail' lead.pk %}"
                                    >{{lead.first_name}}</a
                                >
                            </td>
                            <td class="px-4 py-3">{{lead.last_name}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </section>
</div>
{% endblock %}

leads/templates/leads/category_list.html
{% extends "base.html" %} {% block content %}

<section class="text-gray-700 body-font">
    <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-col text-center w-full mb-20">
            <h1
                class="
                    sm:text-4xl
                    text-3xl
                    font-medium
                    title-font
                    mb-2
                    text-gray-900
                "
            >
                カテゴリー
            </h1>
            <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
                潜在顧客のカテゴリー
            </p>
            <a
                href="{% url 'leads:category-create' %}"
                class="hover:text-blue-500"
                >カテゴリーを作成する</a
            >
        </div>
        <div class="lg:w-2/3 w-full mx-auto overflow-auto">
            <table class="table-auto w-full text-left whitespace-no-wrap">
                <thead>
                    <tr>
                        <th
                            class="
                                px-4
                                py-3
                                title-font
                                tracking-wider
                                font-medium
                                text-gray-900 text-sm
                                bg-gray-200
                                rounded-tl rounded-bl
                            "
                        >
                            名前
                        </th>
                        <th
                            class="
                                px-4
                                py-3
                                title-font
                                tracking-wider
                                font-medium
                                text-gray-900 text-sm
                                bg-gray-200
                            "
                        >
                            顧客数
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="px-4 py-3">未割り当て</td>
                        <td class="px-4 py-3">{{ unassigned_lead_count }}</td>
                    </tr>
                    {% for category in category_list %}
                    <tr>
                        <td class="px-4 py-3">
                            <a
                                class="hover:text-blue-500"
                                href="{% url 'leads:category-detail' category.pk %}"
                                >{{ category.name }}</a
                            >
                        </td>
                        <td class="px-4 py-3">TODO</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</section>

{% endblock content %}

leads/templates/leads/category_update.html
{% extends "base.html" %} {% load tailwind_filters %} {% block content %}

<a class="hover:text-blue-500" href="{% url 'leads:category-list' %}"
    >カテゴリーに戻る</a
>
<div class="py-5 border-t border-gray-200">
    <h1 class="text-4xl text-gray-800">{{ object.name }}</h1>
</div>
<form method="post" class="mt-5">
    {% csrf_token %} {{ form|crispy }}
    <button
        type="submit"
        class="
            w-full
            text-white
            bg-blue-500
            hover:bg-blue-600
            px-3
            py-2
            rounded-md
        "
    >
        更新
    </button>
</form>

{% endblock content %}

leads/templates/leads/lead_category_update.html
{% extends "base.html" %} {% load tailwind_filters %} {% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">
                    顧客
                </h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
                    {{lead.first_name}} {{lead.last_name}}
                </h1>
                <div class="flex mb-4">
                    <a
                        href="{% url 'leads:lead-detail' lead.pk %}"
                        class="
                            flex-grow
                            border-b-2 border-gray-300
                            py-2
                            text-lg
                            px-1
                        "
                        >概要</a
                    >
                    <a
                        href="{% url 'leads:lead-category-update' lead.pk %}"
                        class="
                            flex-grow
                            text-indigo-500
                            border-b-2 border-indigo-500
                            py-2
                            text-lg
                            px-1
                        "
                        >カテゴリー</a
                    >
                    <a
                        href="{% url 'leads:lead-update' lead.pk %}"
                        class="
                            flex-grow
                            border-b-2 border-gray-300
                            py-2
                            text-lg
                            px-1
                        "
                        >編集</a
                    >
                </div>
                <form method="post" action="">
                    {% csrf_token %} {{form|crispy}}
                    <button
                        type="submit"
                        class="
                            w-full
                            text-white
                            bg-blue-500
                            hover:bg-blue-600
                            px-3
                            py-2
                            rounded-md
                        "
                    >
                        移動
                    </button>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock %}

leads/templates/leads/lead_detail.html
{% extends "base.html" %} {% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">
                    顧客
                </h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
                    {{lead.first_name}} {{lead.last_name}}
                </h1>
                <div class="flex mb-4">
                    <a
                        class="
                            flex-grow
                            text-indigo-500
                            border-b-2 border-indigo-500
                            py-2
                            text-lg
                            px-1
                        "
                        >概要</a
                    >
                    <a
                        class="
                            flex-grow
                            border-b-2 border-gray-300
                            py-2
                            text-lg
                            px-1
                        "
                        href="{% url 'leads:lead-category-update' lead.pk %}"
                        >カテゴリー</a
                    >
                    <a
                        href="{% url 'leads:lead-update' lead.pk %}"
                        class="
                            flex-grow
                            border-b-2 border-gray-300
                            py-2
                            text-lg
                            px-1
                        "
                        >編集</a
                    >
                </div>
                <p class="leading-relaxed mb-4">{{lead.description}}</p>
                <div class="flex border-t border-gray-200 py-2">
                    <span class="text-gray-500">年齢</span>
                    <span class="ml-auto text-gray-900">{{lead.age}}</span>
                </div>
                <div class="flex border-t border-gray-200 py-2">
                    <span class="text-gray-500">メール</span>
                    <span class="ml-auto text-gray-900">{{lead.email}}</span>
                </div>
                <div class="flex border-t border-b mb-6 border-gray-200 py-2">
                    <span class="text-gray-500">携帯電話</span>
                    <span class="ml-auto text-gray-900"
                        >{{lead.phone_number}}</span
                    >
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

leads/templates/leads/lead_update.html
{% extends "base.html" %} {% load tailwind_filters %} {% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">
                    顧客
                </h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
                    {{lead.first_name}} {{lead.last_name}}
                </h1>
                <div class="flex mb-4">
                    <a
                        href="{% url 'leads:lead-detail' lead.pk %}"
                        class="
                            flex-grow
                            border-b-2 border-gray-300
                            py-2
                            text-lg
                            px-1
                        "
                        >概要</a
                    >
                    <a
                        href="{% url 'leads:lead-category-update' lead.pk %}"
                        class="
                            flex-grow
                            border-b-2 border-gray-300
                            py-2
                            text-lg
                            px-1
                        "
                        >カテゴリー</a
                    >
                    <a
                        href="{% url 'leads:lead-update' lead.pk %}"
                        class="
                            flex-grow
                            text-indigo-500
                            border-b-2 border-indigo-500
                            py-2
                            text-lg
                            px-1
                        "
                        >編集</a
                    >
                </div>
                <form method="post" action="">
                    {% csrf_token %} {{form|crispy}}
                    <button
                        type="submit"
                        class="
                            w-full
                            text-white
                            bg-blue-500
                            hover:bg-blue-600
                            px-3
                            py-2
                            rounded-md
                        "
                    >
                        更新
                    </button>
                </form>
                <div class="mt-5 py-5 border-t border-gray-200">
                    <a
                        href="{% url 'leads:lead-delete' lead.pk %}"
                        class="
                            w-1/2
                            mt-3
                            text-white
                            bg-red-500
                            border-0
                            py-2
                            px-6
                            focus:outline-none
                            hover:bg-indigo-600
                            rounded
                        "
                        >削除</a
                    >
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}