agents/urls.py
from django.urls import path

from . import views

app_name = "agents"

urlpatterns = [
    path('', views.AgentListView.as_view(), name='agent-list'),
    path('<int:pk>/', views.AgentDetailView.as_view(), name='agent-detail'),
    path('<int:pk>/update/', views.AgentUpdateView.as_view(), name='agent-update'),
    path('<int:pk>/delete/', views.AgentDeleteView.as_view(), name='agent-delete'),
    path('create/', views.AgentCreateView.as_view(), name='agent-create'),
]

djcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView, 
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
    )
from django.urls import path,include
from leads import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.LandingPageView.as_view(), name="landing-page"),
    path('leads/', include("leads.urls", namespace="leads")),
    path('agents/', include("agents.urls", namespace="agents")),
    path('signup/', views.SignupView.as_view(), name="signup"),
    path('reset-password/', PasswordResetView.as_view(), name="reset-password"),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path

from . import views

app_name = "leads"

urlpatterns = [
    path('', views.LeadListView.as_view(), name='lead-list'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='lead-detail'),
    path('<int:pk>/update/', views.LeadUpdateView.as_view(), name='lead-update'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='lead-delete'),
    path('<int:pk>/assign-agent/', views.AssignAgentView.as_view(), name='assign-agent'),
    path('<int:pk>/category/', views.LeadCategoryUpdateView.as_view(), name='lead-category-update'),
    path('create/', views.LeadCreateView.as_view(), name='lead-create'),
    path('create-category/', views.CategoryCreateView.as_view(), name='category-create'),
    path('category/', views.CategoryListView.as_view(), name='category-list'),
    path('category/<int:pk>/update', views.CategoryUpdateView.as_view(), name='category-update'),
    path('category/<int:pk>/delete', views.CategoryDeleteView.as_view(), name='category-delete'),
    path('category/<int:pk>/', views.CategoryDetailView.as_view(), name='category-detail'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>CLCRM</title>
        <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
        <link
            href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css"
            rel="stylesheet"
        />
    </head>
    <body>
        <div class="max-w-7xl mx-auto">
            {% include "navbar.html" %} {% block content %} {%endblock content%}
        </div>
        {% include "scripts.html" %}
    </body>
</html>

templates/landing.html
{%extends "base.html"%} {%block content%}
<section class="text-gray-600 body-font">
    <div
        class="
            container
            mx-auto
            flex
            px-5
            py-24
            items-center
            justify-center
            flex-col
        "
    >
        <img
            class="
                lg:w-2/6
                md:w-3/6
                w-5/6
                mb-10
                object-cover object-center
                rounded
            "
            alt="hero"
            src="../static/images/coding-logo.gif"
        />
        <div class="text-center lg:w-2/3 w-full">
            <h1
                class="
                    title-font
                    sm:text-4xl
                    text-3xl
                    mb-4
                    font-medium
                    text-gray-900
                "
            >
                CRM
            </h1>
            <p class="mb-8 leading-relaxed">
                これはあなたの顧客を管理システムです。
            </p>
            <div class="flex justify-center">
                <a href="{% url 'login' %}">
                    <button
                        class="
                            inline-flex
                            text-white
                            bg-indigo-500
                            border-0
                            py-2
                            px-6
                            focus:outline-none
                            hover:bg-indigo-600
                            rounded
                            text-lg
                        "
                    >
                        始めましょう
                    </button>
                </a>
            </div>
        </div>
    </div>
</section>
{%endblock content%}

templates/navbar.html
<header class="text-gray-600 body-font">
    <div
        class="
            container
            mx-auto
            flex flex-wrap
            p-5
            flex-col
            md:flex-row
            items-center
        "
    >
        <a
            class="
                flex
                title-font
                font-medium
                items-center
                text-gray-900
                mb-4
                md:mb-0
            "
            href="#"
        >
            <img src="../static/images/congle.png" width="50px" alt="" />
            <span class="ml-3 text-xl">CLCRM</span>
        </a>
        <nav
            class="
                md:ml-auto
                flex flex-wrap
                items-center
                text-base
                justify-center
            "
        >
            {% if not request.user.is_authenticated %}
            <a href="{% url 'signup' %}" class="mr-5 hover:text-gray-900"
                >新規作成</a
            >
            {% else %}
            <p></p>
            {% if request.user.is_organisor %}
            <a
                href="{% url 'agents:agent-list' %}"
                class="mr-5 hover:text-gray-900"
                >エージェント</a
            >
            {% endif %}
            <a
                href="{% url 'leads:lead-list' %}"
                class="mr-5 hover:text-gray-900"
                >顧客リスト</a
            >
            {% endif %}
        </nav>
        {% if request.user.is_authenticated %} {{request.user.username}}さん
        <a
            href="{% url 'logout' %}"
            class="
                ml-3
                inline-flex
                items-center
                bg-gray-100
                border-0
                py-1
                px-3
                focus:outline-none
                hover:bg-gray-200
                rounded
                text-base
                mt-4
                md:mt-0
            "
        >
            ログアウト
            <svg
                fill="none"
                stroke="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                class="w-4 h-4 ml-1"
                viewBox="0 0 24 24"
            >
                <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
        </a>
        {% else %}
        <a
            href="{% url 'login' %}"
            class="
                inline-flex
                items-center
                bg-gray-100
                border-0
                py-1
                px-3
                focus:outline-none
                hover:bg-gray-200
                rounded
                text-base
                mt-4
                md:mt-0
            "
        >
            ログイン
            <svg
                fill="none"
                stroke="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                class="w-4 h-4 ml-1"
                viewBox="0 0 24 24"
            >
                <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
        </a>
        {% endif %}
    </div>
</header>

templates/scripts.html
{% load static %}

<script src="{% static 'js/main.js' %}">
    console.log('hello')
</script>